server:
  port: 8080

spring:
  application:
    name: dcg-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

dcg:
  http:
    retry:
      max-attempts: 3
      initial-backoff: 1000  # 初始重试间隔(毫秒)
      max-backoff: 5000      # 最大重试间隔(毫秒)
      multiplier: 2          # 重试间隔倍数
      retry-on-status:       # 需要重试的HTTP状态码
        - 502
        - 503
        - 504
  vas:
    schemes:
      mala:
        base_url: "https://api.mala.com"
        content_type: "json"
        services:
          list:
            endpoint: "/list"
          delete:
            endpoint: "/delete"
        auth:
          type: "bearer_token"
          token: ""
          headers:
            X-Client-ID: "mala-client"
          token_refresh:
            type: "reacquire"
            url: "/api/token"
            method: "POST"
            body:
              username: "${USERNAME}"
              password: "${PASSWORD}"
            token_path: "$.token"
            refresh_before_expiry: "300"
      other_system:
        base_url: "https://other.com"
        content_type: "json"
        services:
          query:
            endpoint: "/query"
        auth:
          type: "oauth2"
          grant_type: "client_credentials"
          client_id: "${CLIENT_ID}"
          client_secret: "${CLIENT_SECRET}"
          token_url: "/oauth/token"
          scope: "read write"
          headers:
            Accept: "application/json"
      legacy_system:
        base_url: "https://legacy.com"
        content_type: "xml"
        services:
          status:
            endpoint: "/status"
        auth:
          type: "basic"
          username: "${BASIC_USER}"
          password: "${BASIC_PASS}"
          headers:
            X-Source: "gateway" 

management:
  endpoints:
    web:
      exposure:
        include: refresh 